services:
  - type: web
    name: task-management-backend
    env: node
    plan: starter
    rootPath: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        from: env

  - type: static
    name: task-management-frontend
    env: static
    plan: starter
    rootPath: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
